server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/jobscheduler
    username: root
    password: Magic@1992
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

  spring:
    config:
      activate:
        on-profile: docker-mysql
    datasource:
      url: jdbc:mysql://localhost:3307/jobscheduler   # containerized mysql
      username: root
      password: root

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: job-workers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

jobs:
  topic: ${JOBS_TOPIC:jobs.dispatch}
  scheduler:
    poll-ms: 3000
